version: "3.8"

services:
  db:
    image: postgres:15
    container_name: rule-engine-db
    environment:
      POSTGRES_DB: rule_engine
      POSTGRES_USER: rule_user
      POSTGRES_PASSWORD: rule_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: rule-engine-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/rule_engine"
      SPRING_DATASOURCE_USERNAME: rule_user
      SPRING_DATASOURCE_PASSWORD: rule_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped

volumes:
  pgdata:
